# Generated by Django 5.1.1 on 2024-10-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostainvestimento',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
