# Generated by Django 5.1.1 on 2024-10-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0005_alter_metricas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
